
enum ErrorType {
    SUCCESS = 0,
    FAILURE = 1,
    APPSERVER_UNREGISTER = 2,
    INVALID_APPSERVER_ID = 3,
    INVALID_TOKEN = 4,
    INCOMPLETE_INFO = 5,
    APPSERVER_DUP_REGISTER = 6,
    CONNECT_FAILURE = 7,
}

