######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 10 19:46:20 2008
######################################################################

TEMPLATE = app
TARGET = fileviewer
DEPENDPATH += . release
INCLUDEPATH += .

QT += widgets
# Input
HEADERS += fileviewer.h
SOURCES += fileviewer.cpp main.cpp
RESOURCES += fileviewer.qrc
TRANSLATIONS += fileviewer_zh.ts
