######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 10 21:53:29 2008
######################################################################

TEMPLATE = app
TARGET = mainwindow
DEPENDPATH += . release
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += mainwindow.h
SOURCES += main.cpp mainwindow.cpp
RESOURCES += mainwindow.qrc
