######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 10 22:06:33 2008
######################################################################

TEMPLATE = app
TARGET = paintbasic
DEPENDPATH += .
INCLUDEPATH += .
QT += core gui widgets

# Input
HEADERS += mainwidget.h paintarea.h
SOURCES += main.cpp mainwidget.cpp paintarea.cpp
RESOURCES += paintbasic.qrc
TRANSLATIONS += paintbasic_zh.ts
