#ifndef MQTT_RPC_MQTT_RPC_ERROR_ENUM_INC
#define MQTT_RPC_MQTT_RPC_ERROR_ENUM_INC

namespace mqtt_rpc {

enum MqttRpcErrorEnum {
	MQTT_CLIENT_STATUS_IS_DISCONNECTED = 1,
	MQTT_CLIENT_STATUS_IS_CONNECTED = 2,
	MQTT_CLIENT_STATUS_IS_CONNECTING = 3,
	MQTT_RPC_CLIENT_SUBSCRIBE_TOPIC_IS_NULL = 4,
	MQTT_RPC_CLIENT_PUBLISH_TOPIC_IS_NULL = 5,
};

}	// mqtt_rpc

#endif
