load("//tools:cpplint.bzl", "cpplint")

package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "timer_test",
    srcs = [
            "main.cc",
            ],
    deps = [
        "//cyber",
    ],
)

cpplint()

